# Generated by Django 5.1.6 on 2025-03-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANT', 'Restaurant'), ('ATTRACTION', 'Tourist Attraction')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('sustainability_score', models.IntegerField(default=0)),
            ],
        ),
    ]
