# Generated by Django 5.1.6 on 2025-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbusiness',
            name='price_tier',
            field=models.CharField(choices=[('low', 'Low (< $500)'), ('medium', 'Medium ($500–$1,500)'), ('high', 'High (> $1,500)')], default='medium', help_text='Business price tier for budget filtering', max_length=10),
        ),
    ]
