# Generated by Django 5.2 on 2025-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='packages',
            field=models.ManyToManyField(blank=True, to='frontend.trippackage'),
        ),
    ]
