# Generated by Django 5.1.6 on 2025-03-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='travel_style',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
